name: Build Windows GUI Executable

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows-gui:
    runs-on: windows-latest

    steps:
      # Kodun deposunu al
      - uses: actions/checkout@v3

      # Go kurulumu
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      # Go GUI uygulamasını derle
      - name: Build Windows GUI Executable
        run: go build -ldflags "-s -w -H=windowsgui" -o myprogram.exe ./main.go

      # Oluşan exe’yi artifact olarak yükle
      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-gui-exe
          path: myprogram.exe
